# YAML-076: Bias Stress Test
# QA Focus: Parity score > 0.9
# Validation: 25-point checklist required

entrenar: "1.0"
name: "bias-audit"
version: "1.0.0"
description: "Fairness testing with demographic parity verification"

seed: 42

audit:
  type: "bias"
  protected_attr: "gender"
  favorable_outcome: 1
  metrics:
    - "demographic_parity"
    - "equalized_odds"
    - "calibration"
    - "predictive_parity"
  threshold: 0.9
  subgroups: ["male", "female", "non_binary"]

data:
  source: "./data/hiring.parquet"
  loader:
    batch_size: 64
    shuffle: false

model:
  source: "./models/hiring_classifier.safetensors"
  device: "auto"

output:
  dir: "./outputs/bias-audit-${timestamp}"
  report:
    enabled: true
    format: "html"
    include_plots: true
