# YAML-014: Automated Fix Suggestion
# QA Focus: Top 3 suggestions contain correct fix
# Validation: 25-point checklist required
# Note: CITL features require separate integration

model:
  path: ./models/mock.gguf
  layers: []

data:
  train: ./data/train.parquet
  batch_size: 32

optimizer:
  name: adam
  lr: 0.001

training:
  epochs: 1
  output_dir: ./outputs/citl-suggest
