# YAML-005: Deterministic Replay
# QA Focus: Run twice; artifacts must have identical SHA256
# Validation: 25-point checklist required (Heijunka verification)

model:
  path: ./models/mock.gguf
  layers: []

data:
  train: ./data/train.parquet
  batch_size: 32

optimizer:
  name: sgd
  lr: 0.01
  momentum: 0.9

training:
  epochs: 3
  output_dir: ./outputs/deterministic
