# YAML-034: Model Distillation
# QA Focus: Student matches 90% of teacher performance
# Validation: 25-point checklist required

model:
  path: ./models/mock.gguf
  layers: []

data:
  train: ./data/train.parquet
  batch_size: 8

optimizer:
  name: adamw
  lr: 0.0001

training:
  epochs: 5
  output_dir: ./outputs/distill
