# YAML-048: Outlier Detection
# QA Focus: Z-score threshold logic works
# Validation: 25-point checklist required

model:
  path: ./models/mock.gguf
  layers: []

data:
  train: ./data/train.parquet
  batch_size: 64

optimizer:
  name: adam
  lr: 0.001

training:
  epochs: 10
  output_dir: ./outputs/outlier
