# YAML-100: The "Golden Run" (Final Verification)
# QA Focus: ALL 25 CHECKS MUST PASS. Peer review required.
# Validation: 25-point checklist required

model:
  path: ./models/mock.gguf
  layers: []

data:
  train: ./data/train.parquet
  batch_size: 64

optimizer:
  name: adamw
  lr: 0.0001
  weight_decay: 0.01

training:
  epochs: 10
  grad_clip: 1.0
  save_interval: 1
  output_dir: ./outputs/release
