# YAML-083: Ruchy Session Resume
# QA Focus: Session state restored exactly
# Validation: 25-point checklist required

entrenar: "1.0"
name: "session-resume"
version: "1.0.0"
description: "Stateful session management for continuity"

seed: 42

session:
  id: "train-001"
  auto_save: true
  resume_on_crash: true
  state_dir: "./sessions"

data:
  source: "mnist"
  loader:
    batch_size: 64
    shuffle: true

model:
  source: "builtin://mlp"
  device: "auto"

optimizer:
  name: "adam"
  lr: 0.001

training:
  epochs: 20
  checkpoint:
    save_every: 100
    keep_last: 5

output:
  dir: "./outputs/session-${session.id}"
